Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -18,19 +18,6 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-#      - name: Run Trivy vulnerability scanner - FS mode
-#        uses: aquasecurity/trivy-action@0.5.1
-#        with:
-#          scan-type: 'fs'
-#          security-checks: 'vuln,config,secret'
-#          hide-progress: false
-#          format: 'table'
-#        env:
-#          AQUA_KEY: ${{ secrets.AQUA_KEY }}
-#          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-#          TRIVY_RUN_AS_PLUGIN: 'aqua'
-#          TRIGGERED_BY: 'PUSH'
-#          GITHUB_TOKEN: ${{ github.token }}
       - uses: mr-smithers-excellent/docker-build-push@v5
         name: Build & push Docker image
         with:
@@ -39,16 +26,40 @@ jobs:
           registry: docker.io
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
+  linux:
+    name: Manifest
+    runs-on: ubuntu-latest
+    steps:
+      - name: Run Trivy vulnerability scanner - FS mode
+        uses: aquasecurity/trivy-action@0.5.1
+        with:
+          scan-type: 'fs'
+          security-checks: 'vuln,config,secret'
+          hide-progress: false
+          format: 'table'
+        env:
+          AQUA_KEY: ${{ secrets.AQUA_KEY }}
+          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+          TRIVY_RUN_AS_PLUGIN: 'aqua'
+          TRIGGERED_BY: 'PUSH'
+          GITHUB_TOKEN: ${{ github.token }}
       - name: Manifest Generation
         run: |
-          #export BILLY_SERVER=https://prod-aqua-billy.codesec.aquasec.com
+          export BILLY_SERVER=https://prod-aqua-billy.codesec.aquasec.com
           curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          #BINDIR="."
-          sh install.sh
-          rm install.sh 
-          rm install.sh.checksum
-          ./billy generate --access-token "${{ secrets.GITHUB_TOKEN }}" --aqua-key "${{ secrets.AQUA_KEY }}" --aqua-secret "${{ secrets.AQUA_SECRET }}" --artifact-path "biagiodesimone/windowsvuln:${{ github.sha }}" 
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "biagiodesimone/windowsvuln:${{ env.tag-version }}" 
+
             # The docker image name:tag of the newly built image
             # --artifact-path "my-image-name:${{ env.tag-version }}" 
             # OR the path to the root folder of your project. I.e my-repo/my-app 
